---
# Create self-signed Issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: config-sync-selfsigned-issuer
  namespace: config-sync-system
spec:
  selfSigned: {}
---
# Create CA certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: config-sync-ca
  namespace: config-sync-system
spec:
  isCA: true
  commonName: config-sync-ca
  secretName: config-sync-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: config-sync-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
# Create CA Issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: config-sync-ca-issuer
  namespace: config-sync-system
spec:
  ca:
    secretName: config-sync-ca-secret
---
# Create Webhook certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: config-sync-webhook-cert
  namespace: config-sync-system
spec:
  secretName: config-sync-webhook-cert
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
    - zyql
  commonName: config-sync-webhook-service.config-sync-system.svc
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - config-sync-webhook-service
  - config-sync-webhook-service.config-sync-system
  - config-sync-webhook-service.config-sync-system.svc
  - config-sync-webhook-service.config-sync-system.svc.cluster.local
  issuerRef:
    name: config-sync-ca-issuer
    kind: Issuer
    group: cert-manager.io
