apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner-aios
  namespace: gitlab-runner
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: gitlab-runner-aios
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitlab-runner-aios
  template:
    metadata:
      labels:
        app: gitlab-runner-aios
      annotations:
        checksum/configmap: 430666f75c161e006ce0f3dd74a8fb4a0e483705a2cd4eac687b040fa95607ca
        checksum/secrets: 7ffda4b22c3a870429f546ba932740c4311df953c831934fcc3eeac691794dbd
    spec:
      securityContext: 
        fsGroup: 65533
        runAsUser: 100
      terminationGracePeriodSeconds: 3600
      serviceAccountName: gitlab-runner
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: gitlab-runner-aios
        image: reg.zyql.com/library/gitlab-runner:alpine-v18.6.1
        imagePullPolicy: "IfNotPresent"
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        lifecycle:
          preStop:
            exec:
              command: ["/entrypoint", "unregister", "--all-runners"]
        command: ["/usr/bin/dumb-init", "--", "/bin/bash", "/configmaps/entrypoint"]
        env:        
        - name: CI_SERVER_URL
          value: "https://git.zyql.com/"
        - name: RUNNER_EXECUTOR
          value: "kubernetes"
        - name: REGISTER_LOCKED
          value: "true"
        - name: RUNNER_TAG_LIST
          value: ""
        - name: SESSION_SERVER_ADDRESS
          value: ""
        livenessProbe:
          exec:
            command: ["/bin/bash", "/configmaps/check-live", "3"]
          initialDelaySeconds: 60
          timeoutSeconds: 4
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/usr/bin/pgrep","gitlab.*runner"]
          initialDelaySeconds: 60
          timeoutSeconds: 4
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
        ports:
        - name: "metrics"
          containerPort: 9252
        volumeMounts:
        - name: projected-secrets
          mountPath: /secrets
        - name: etc-gitlab-runner
          mountPath: /home/gitlab-runner/.gitlab-runner
        - name: configmaps
          mountPath: /configmaps
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
      volumes:
      - name: runner-secrets
        emptyDir:
          medium: "Memory"
      - name: etc-gitlab-runner
        emptyDir:
          medium: "Memory"
      - name: projected-secrets
        projected:
          sources:
            - secret:
                name: gitlab-runner
                items:
                  - key: runner-registration-aios-token
                    path: runner-registration-token
                  - key: runner-aios-token
                    path: runner-token
            - secret:
                name: docker-registry
                items:
                  - key: .dockerconfigjson
                    path: config.json
            - secret:
                name: app-signing-keys
                items:
                  - key: password
                    path: password
                  - key: zyql-aios-keystore-base64
                    path: zyql-aios-keystore-base64
            - secret:
                name: nexus-auth
                items:
                  - key: nexus-url
                    path: nexus-url
                  - key: nexus-username
                    path: nexus-username
                  - key: nexus-password
                    path: nexus-pasword
            - secret:
                name: feishu-auth
                items:
                  - key: feishu-app-id
                    path: feishu-app-id
                  - key: feishu-app-secret
                    path: feishu-app-secret
            - secret:
                name: gitlab-pull-auth
                items:
                  - key: gitlab-username
                    path: gitlab-username
                  - key: gitlab-password
                    path: gitlab-password
            - secret:
                name: volcengine-tos-auth
                items:
                  - key: tos-endpoint
                    path: tos-endpoint
                  - key: tos-region
                    path: tos-region
                  - key: tos-bucket
                    path: tos-bucket
                  - key: tos-access-key
                    path: tos-access-key
                  - key: tos-secret-key
                    path: tos-secret-key
            - secret:
                name: jira-auth
                items:
                  - key: jira-token
                    path: jira-token
      - name: configmaps
        configMap:
          name: gitlab-runner
