apiVersion: rbac.authorization.k8s.io/v1
kind: "Role"
metadata:
  name: gitlab-runner
  labels:
    app: gitlab-runner
  namespace: gitlab-runner
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list","watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create","delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","watch"]
- apiGroups: [""]
  resources: ["pods/attach","pods/exec"]
  verbs: ["get","create","patch","delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","delete","get","update"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create","get"]
