apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
  labels:
    app: gitlab-runner
    release: gitlab-runner
imagePullSecrets:
  - name: docker-registry
