apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: alibaba-rrsa-store
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    alibaba:
      regionID: cn-shanghai
      auth:
        rrsa:
          oidcProviderArn: acs:ram::1893149804346956:oidc-provider/ack-rrsa-caac1a2edb593462fac1a8bd532555e01
          oidcTokenFilePath: /var/run/secrets/ack.alibabacloud.com/rrsa-tokens/oidc-token
          roleArn: acs:ram::1893149804346956:role/external-secret-ack
          sessionName: external-secrets
