apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: gitlab-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: alibaba-rrsa-store
    kind: ClusterSecretStore
  target:
    name: docker-registry
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .registry }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: /zyql/infra/docker/registry/secret
        property: username
    - secretKey: password
      remoteRef:
        key: /zyql/infra/docker/registry/secret
        property: password
    - secretKey: registry
      remoteRef:
        key: /zyql/infra/docker/registry/secret
        property: registry
